### ISSUE TITLE
Forgotten </div>

### ISSUE THREAD

**Issue by bogwero** [TeamEver/everblock#11]
```
<!-- Module Ever Block -->
{if isset($everblock) && $everblock}
        {foreach from=$everblock item=item}
            {if isset($item.block.add_container) && $item.block.add_container == 1}
            <div class="container">
            {/if}
            <div class="everblock everblock-{$item.block.id_everblock|escape:'htmlall':'UTF-8'} {$item.block.css_class|escape:'htmlall':'UTF-8'} {$item.block.bootstrap_class|escape:'htmlall':'UTF-8'} everhook-{$everhook|escape:'htmlall':'UTF-8'}" id="everblock-{$item.block.id_everblock|escape:'htmlall':'UTF-8'}" data-everposition="{$item.block.position|escape:'htmlall':'UTF-8'}" data-everhook="{$everhook|escape:'htmlall':'UTF-8'}"{if isset($item.block.background) && $item.block.background} style="background-color:{$item.block.background|escape:'htmlall':'UTF-8'};"{/if}>
                {$item.block.content nofilter}
            </div>
            {if isset($item.block.add_container) && $item.block.add_container == 1}
            </div>
            {/if}
        {/foreach}
    </div> **<- Did you forget about this </div> ?**
{/if}
<!-- /Module Ever Block -->
```

**Comment by Luifer-dnk** [comment]
> $item.block.content nofilter

Are you referring to this file?

![image](https://github.com/TeamEver/everblock/assets/31345705/5d286f37-14ca-4a08-8d90-7d6f5529cb2e)


Which version do you use?

**Comment by bogwero** [comment]
Hi,
First of all, thank you for the great module and I apologize for not being more specific.
Yes, this is the file: https://github.com/TeamEver/everblock/blob/master/views/templates/hook/everblock.tpl
I am using the latest 4.11 everblock plugin version. 
To replicate the issue please change position of the block, for example on the front page, from last position (3 in my case) to 2 or 1, before the Featured Products or Best sellers and see that the `</div>` in question will break the layout of the page.

Kind regards!

**Comment by Luifer-dnk** [comment]
@bogwero you can close thread by solved ?

Many thanks.
