### ISSUE TITLE
Not work with latest version 3.0.2 of PrettyBlocks.

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#12]
Hi.

When upgrading to PrettyBlocks version 3.0.1 or 3.0.2 the loading and configuration of PrettyBlocks is broken.

Greetings.

**Comment by A2P2R** [comment]
hi @Luifer-dnk 

I had the same problem, but since updating to pretty blocks 3.0.3 I no longer have this problem.

greetings

**Comment by Luifer-dnk** [comment]
The problem continues, but it is on the part of Pretty Blocks and Cloudflare.
For some reason it doesn't charge properly.
In tests on localhost it works correctly.

**Comment by Luifer-dnk** [comment]
Solved.

In cloudflare you have to disable Rocket Loader loading.

**Comment by Luifer-dnk** [comment]
Closed for fix when setting up Cloudflare.
