### ISSUE TITLE
It does not backup the blocks.

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#13]
Two errors:

![image](https://github.com/TeamEver/everblock/assets/31345705/94a2ce98-e64b-4929-b7f1-d593a86bd934)

Many thanks !!!

**Comment by Luifer-dnk** [comment]
Sorry, Bacup made it perfectly !!!

Error is for another cause.

Continue to investigate !!!

**Comment by CySSoO** [comment]
Hi @Luifer-dnk 
Latest commit will fix the error message, postSuccess & postErrors weren't array on backup & restore tools
You can try using latest commit or latest tag

**Comment by Luifer-dnk** [comment]
> Hi @Luifer-dnk Latest commit will fix the error message, postSuccess & postErrors weren't array on backup & restore tools You can try using latest commit or latest tag

I see...

Many thanks.
