### ISSUE TITLE
Issue on Admin Product page (hook displayAdminProductsExtra)

### ISSUE THREAD

**Issue by vmulot** [TeamEver/everblock#14]
Hi, i'm facing an issue when accessing admin product form.
`Warning: Trying to access array offset on value of type null`

`HookCore::callHookOn(object(Everblock), 'displayAdminProductsExtra', array('_ps_version' => '8.1.3', 'request' => object(Request), 'route' => 'admin_products_edit', 'id_product' => 26164, 'cookie' => object(Cookie), 'cart' => null, 'altern' => 1))`

prestashop 8.1.3
everblock 5.5.1

I have some other modules hooked on this hook . when disabling everblock module, no more error showing.
any idea why?  thanks.

**Comment by vmulot** [comment]
changes needed :
`<textarea id="everblock_content_{$language.id_lang|escape:'htmlall':'UTF-8'}" name="everblock_content_{$language.id_lang|escape:'htmlall':'UTF-8'}" class="form-control autoload_rte">{if isset({$everpstabs->content[$language.id_lang]}) && {$everpstabs->content[$language.id_lang]} != ''}{$everpstabs->content[$language.id_lang]|escape:'htmlall':'UTF-8'}{/if}</textarea>`

to 
`<textarea id="everblock_content_{$language.id_lang|escape:'htmlall':'UTF-8'}" name="everblock_content_{$language.id_lang|escape:'htmlall':'UTF-8'}" class="form-control autoload_rte">{if isset($everpstabs->content[$language.id_lang]) && $everpstabs->content[$language.id_lang] != ''}{$everpstabs->content[$language.id_lang]|escape:'htmlall':'UTF-8'}{/if}</textarea>`

**Comment by CySSoO** [comment]
Thanks for your pull request, it has been merged
