### ISSUE TITLE
Versión 5.5.3 crash Back Office.

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#16]
HTTP ERROR 500 on Back Office.

Nothing work on Back Office.

PS 8.1.3
PHP 8.1.127

Many thanks.

**Comment by CySSoO** [comment]
Hi @Luifer-dnk 
Could you enable dedbug mode and show me 500 error message ?

**Comment by CySSoO** [comment]
Latest version should fix 500 error

**Comment by Luifer-dnk** [comment]
V5.5.4 working perfect !!!

Many thanks.
