### ISSUE TITLE
Error on install and module...

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#18]
Compile error on load:

![image](https://github.com/TeamEver/everblock/assets/31345705/e654b393-5cee-4dff-84d4-a4a43e204c88)

Many thanks !!!

**Comment by CySSoO** [comment]
Good morning
The problem is due to the use of the Ever Checkout Step module, which is now embedded in Everblock
The error should nevertheless be corrected in the latest version of the module

**Comment by Luifer-dnk** [comment]
To last version...

Thanks.
