### ISSUE TITLE
Consider using GitHub releases for releases

### ISSUE THREAD

**Issue by cruftex** [TeamEver/everblock#2]
Many thanks for providing a block module! We just stumbled over it and consider using it in our projects.

However, once we use it in production it would be good to know what changes are done between releases and what we might need to do when upgrading the module.

Please consider doing releases view GitHub releases, so you can add some text describing the changes. This way its also more easy to follow the project.

**Comment by CySSoO** [comment]
Hello and thank you for your interest in this module.
Does this correspond to your request?
Best regards

https://github.com/TeamEver/everblock/releases/tag/V4.4.2

**Comment by CySSoO** [comment]
Good morning
This issue being open and currently unanswered, it is now closed
Do not hesitate to recreate an issue if your concern is not resolved by detailing the problem encountered
Best regards
