### ISSUE TITLE
empty space in PHP file generate error 

### ISSUE THREAD

**Issue by pawelkierklo** [TeamEver/everblock#21]
https://github.com/TeamEver/everblock/blob/4dc25cd7c4e7776d567c26a4a0b399f3631d4c66/controllers/admin/AdminEverBlockController.php#L1

![image](https://github.com/TeamEver/everblock/assets/26326399/5b1bd0e5-9f97-4c2f-b8e2-41c00127202d)

**Comment by CySSoO** [comment]
Hello @pawelkierklo 
Fix has been pushed on latest release
https://github.com/TeamEver/everblock/releases/tag/V5.8.2
