### ISSUE TITLE
Error in hook caused by the flag ?

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#22]
Error in hook caused by the flag.

The product thumbnail also generates the same error.

I have not set any flags.

Test on PS 8.1.7 and PHP 8.1

![image](https://github.com/user-attachments/assets/a8941895-29e4-4b1b-9c85-f4653eddb15b)

**Comment by Luifer-dnk** [comment]
Well:

` if (is_array($display)) {
    // And notify the developer in debug mode.
    if (_PS_MODE_DEV_) {
        trigger_error(sprintf(
            'Module %s returned an array on hook %s. This is not allowed, the response must be joinable to a string.',
            $moduleInstance->name,
            $hook_name
        ), E_USER_NOTICE);
    }
}`

With debug mode off work ok.

**Comment by CySSoO** [comment]
Hello @Luifer-dnk 
Indeed it is caused by the module at the flags level
Could you try with this release ?
https://github.com/TeamEver/everblock/releases/tag/V5.9.1

**Comment by Luifer-dnk** [comment]
> Hello @Luifer-dnk Indeed it is caused by the module at the flags level Could you try with this release ? https://github.com/TeamEver/everblock/releases/tag/V5.9.1

Same issue with v5.9.1.

**Comment by Luifer-dnk** [comment]
Fixed !!!

Many thanks.
