### ISSUE TITLE
Hook problem (data is array)

### ISSUE THREAD

**Issue by pawelkierklo** [TeamEver/everblock#24]
Everblock 5.9.0 and newest
Problem in PS 8.1.3 on PHP 8.1  (Hummingbird theme)
error showing on everywhere in every page with same line code

![image](https://github.com/user-attachments/assets/f5801c12-3da5-4d93-b923-9a39dcad4d8f)

**Comment by CySSoO** [comment]
Hi @pawelkierklo 
As this issue is already being processed here, I am closing this one so as not to have a duplicate
https://github.com/TeamEver/everblock/issues/22
Thank you for your understanding
