### ISSUE TITLE
before send email in complete checkout - warning

### ISSUE THREAD

**Issue by pawelkierklo** [TeamEver/everblock#25]
> Warning: foreach() argument must be of type array|object, null given in /usr/www/users/meters/modules/everblock/everblock.php on line 1572

when order is successfully created in shop (finalize form checkout)

**Comment by pawelkierklo** [comment]
> Warning: foreach() argument must be of type array|object, null given in /usr/www/users/meters/modules/everblock/everblock.php on line 1623
again

**Comment by CySSoO** [comment]
Thanks for feedback and help @pawelkierklo 
Suggestion has been committed on this version : 
https://github.com/TeamEver/everblock/releases/tag/V6.1.5
Could you try again ? Unfortunately I still can't reproduce the problem (but i'm still working on it)
Thanks again
