### ISSUE TITLE
[SPAM] - Contact Form - How to prevent ?

### ISSUE THREAD

**Issue by bicipres** [TeamEver/everblock#26]
Hello,

It appears that bots are spamming from the module's contact /everblock/controllers/front/contact.php file.

**Observation:**

Here is the type of message received in number on each language version of the site.**

```
Un message a été envoyé depuis votre site XXXXXXXXX
La demande est la suivante : 
token: d7cd9700ad10ffc458c8a2947430cfxx isolang: sv id lang: 10 module: everblock controller: contact fc: module Client IP: 185.28.182.18X Client browser: Google Chrome Client platform: Windows 
```
Here is the frequency:

**Question: How do I add a recaptcha to this form?**

Is there already a way to fill in a recaptcha key in the configuration field?

Regards,

**Comment by CySSoO** [comment]
Hello
On contact front controller, a hook is triggered
https://github.com/TeamEver/everblock/blob/master/controllers/front/contact.php#L40
If form is empty after hook is triggered, mail wont be sent. Maybe you can use https://github.com/nenes25/eicaptcha in order to trigger  Google Recaptcha

**Comment by CySSoO** [comment]
I've made an update for recaptcha
Could you try with this release ?
https://github.com/TeamEver/everblock/releases/tag/V6.3.1

**Comment by bicipres** [comment]
Hello @CySSoO,

I did the upgrade and until now, I don't have any spam message.

I will close the ticket.

Thanks!
