### ISSUE TITLE
Version 4.6.3 and 4.6.4 do not show anything!!!

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everblock#4]
I have tested version 4.4.4, and it perfectly loads the hooks with the content, but in versions 4.6.3 and 4.6.4, it does not show anything in any hook.
Does not generate any errors in debug mode.

PS 1.7.8.9 & PHP 7.4.33 - 8.1.18
PS 8.0.4 & PHP 7.4.33 - 8.1.18

Thanks.

**Comment by CySSoO** [comment]
Good morning
The latest release of the module should correct your problem
You can download it [here](https://github.com/TeamEver/everblock/releases/tag/V4.7.1)
Best regards

**Comment by Luifer-dnk** [comment]
Many thanks...

Now working perfectly!!!
