### ISSUE TITLE
Error on path /modules/everblock//views/js/custom-compressed1.js

### ISSUE THREAD

**Issue by bicipres** [TeamEver/everblock#5]
Hi, 

It's look like that there is an error with path for views/js/custom-compressed1.js which have to slashes.

![image](https://github.com/TeamEver/everblock/assets/136792892/86bd815d-98bd-49bc-9958-ed5e0574fad0)

Prestashop version 1.7.8.9.
PHP : 7.4
Module Version : v4.7.1 

Regards,

**Comment by CySSoO** [comment]
Hello
A new release has been published, could you try it and tell me if it solves your problem ?
Best regards

**Comment by bicipres** [comment]
Hi CySSoO,
First of all, thanks for your hard work. 
Sorry for my late reply because i was busy. I did the update but i have the same error unfortunately.
Best regards,

**Comment by CySSoO** [comment]
Could you try to delete views/js/custom-compressed1.js and then clear cache ?
Best regards

**Comment by bicipres** [comment]
H did it but results are same.

Steps :
- delete views/js/custom-compressed1.js 
- Clean cache via everblockbutton
- Clean cache prestashop
- Reinstall the new version of the module
- delete views/js/custom-compressed1.js 
- Clean cache via everblockbutton
- Clean cache prestashop

Best regards,

**Comment by CySSoO** [comment]
Good morning
Does the latest release solve your problem?
[https://github.com/TeamEver/everblock/releases/tag/V4.9.0](https://github.com/TeamEver/everblock/releases/tag/V4.9.0)
You will need to empty the cache of your store for the changes to be taken into account.

**Comment by A2P2R** [comment]
Hello, I have the same problem. I tried deleting the file and clearing the cache, but it's the same.

I have module version 4.9.6, do you have a solution? (ps 8.1.1)

![Snag_6cadc60](https://github.com/TeamEver/everblock/assets/85064700/55f9fad7-063a-4bd8-ae77-9eb8af8f0822)

**Comment by A2P2R** [comment]
> Hello @CySSoO , I have the same problem. I tried deleting the file and clearing the cache, but it's the same.
> 
> I have module version 4.9.6, do you have a solution? (ps 8.1.1)
> 
> ![Snag_6cadc60](https://user-images.githubusercontent.com/85064700/268416308-55f9fad7-063a-4bd8-ae77-9eb8af8f0822.png)

hi @CySSoO , I have the impression that despite the latest update, we have the same problem.

**Comment by CySSoO** [comment]
Hello @A2P2R 
Have you tried latest module version ?
https://github.com/TeamEver/everblock/releases/tag/V4.10.2
Best regards

**Comment by A2P2R** [comment]
> Hello @A2P2R 
> 
> Have you tried latest module version ?
> 
> https://github.com/TeamEver/everblock/releases/tag/V4.10.2
> 
> Best regards

Hi @CySSoO, 

Yes ! And I am the same problems.

Thank you for your help

**Comment by CySSoO** [comment]
Ok, if the file is empty, in fact the internet browser can output a 404
This commit
https://github.com/TeamEver/everblock/commit/7a5a9ca1833a13abe261cf83b8d5fe034ae93341
Can solve your problem. This checks if the file is present on your server, and if it is not empty
Can you try by just updating the following file @A2P2R  ?
https://github.com/TeamEver/everblock/blob/master/everblock.php
This will be on the next release

**Comment by A2P2R** [comment]
Hi @CySSoO 

thank you very much for your feedback! it works now, I can confirm.

I'd like to take this opportunity to thank you for your work on this module.

thank you

**Comment by CySSoO** [comment]
Thanks for helping and supporting us !
