### ISSUE TITLE
Layout block with Prettyblock

### ISSUE THREAD

**Issue by A2P2R** [TeamEver/everblock#7]
Hi @CySSoO,

I'm trying to use the everblock "layout" component in prettyblock. But I have a little problem.
When I define the width of each column (50% in my example for the 2 attached columns), it works fine.
However, it should line up on the same line as it doesn't exceed 100%. 

I've tested this on several instances, but it seems to be a general problem.

thanks for your help
![block2](https://github.com/TeamEver/everblock/assets/85064700/68ef8dea-b2e1-4218-a8f7-c5fcf9ad0929)

**Comment by Luifer-dnk** [comment]
> Hi @CySSoO,
> 
> I'm trying to use the everblock "layout" component in prettyblock. But I have a little problem. When I define the width of each column (50% in my example for the 2 attached columns), it works fine. However, it should line up on the same line as it doesn't exceed 100%.
> 
> I've tested this on several instances, but it seems to be a general problem.
> 
> thanks for your help ![block2](https://user-images.githubusercontent.com/85064700/275292970-68ef8dea-b2e1-4218-a8f7-c5fcf9ad0929.jpg)

Temporary solution.

open the file:
/modules/prettyblocks/views/templates/front/zone.tpl

And add: style="display: flex;"

![image](https://github.com/TeamEver/everblock/assets/31345705/c3dce504-4ae3-46a6-bd6d-37f10136fea2)

**Result**:

![image](https://github.com/TeamEver/everblock/assets/31345705/6223d561-082c-4d97-9cd4-6a0cb0169c45)

![image](https://github.com/TeamEver/everblock/assets/31345705/346e64d9-eeb8-44a7-86ba-6e6608d58988)

Greetings.

**Comment by A2P2R** [comment]
hello, first of all thank you very much for your feedback! 

unfortunately, this solution doesn't really work because it applies to all pretty blocks on the website. 
this means that it aligns all the pretty block blocks on the same page on the same line. for this to work properly, it would have to be only for the "layout" block with a rule that returns to the line when it has exceeded 100% of the layout.

thanks again for your help ;)

**Comment by A2P2R** [comment]
hi @CySSoO 

I've updated to the latest version of everblock, but it doesn't seem to solve the problem.

thanks ;)

**Comment by Luifer-dnk** [comment]
> hi @CySSoO
> 
> I've updated to the latest version of everblock, but it doesn't seem to solve the problem.
> 
> thanks ;)

Hi.

With two col-md-6 on <div class="col-md-6"> on the same block, you can make.

![image](https://github.com/TeamEver/everblock/assets/31345705/8c3ab50c-2e7b-4706-8839-3d3afa142dcc)

![image](https://github.com/TeamEver/everblock/assets/31345705/9ce6a254-0c09-416b-a9d4-faec4db563a5)

![image](https://github.com/TeamEver/everblock/assets/31345705/c6811101-82b3-4197-a1a1-4291d674cbb7)

Mod CSS and get the correct design.

I think it is more practical than assembling two blocks.

Greetings-

**Comment by A2P2R** [comment]
hi @Luifer-dnk 

thank you very much for your feedback. unfortunately, it doesn't work : elements are placed one under the other. i think it's because of my theme (i use cartzilla orignal theme with prettyblock). 

thanks again for your help

**Comment by bogwero** [comment]
Hi,
Try deleting the orphan </div> from the file https://github.com/TeamEver/everblock/blob/master/views/templates/hook/everblock.tpl on line 32 (delete line 32).
This fixed it for me.

**Comment by A2P2R** [comment]
> Hi,
> 
> Try deleting the orphan` </div> `from the file https://github.com/TeamEver/everblock/blob/master/views/templates/hook/everblock.tpl on line 32 (delete line 32).
> 
> This fixed it for me.

Hi @bogwero 

I tested it quickly and it doesn't seem to work. On the other hand, I will take a closer look at my side to find out if the problem is not here now. are you using the cartzilla theme?

Thanks

**Comment by bogwero** [comment]
> > Hi,
> > Try deleting the orphan`</div>`from the file https://github.com/TeamEver/everblock/blob/master/views/templates/hook/everblock.tpl on line 32 (delete line 32).
> > This fixed it for me.
> 
> Hi @bogwero
> 
> I tested it quickly and it doesn't seem to work. On the other hand, I will take a closer look at my side to find out if the problem is not here now. are you using the cartzilla theme?
> 
> Thanks

Hi,
Unfortunately I don't know what could be the problem in your case, however I'm positive that div wasn't supposed to be there in the latest version, 4.11.
I am using Falcon theme (https://github.com/Oksydan/falcon) it's a great theme but it's meant only for advanced users who know how to work with webpack, node, npm, etc, because you need to compile it before you can use it.

Kind regards!

**Comment by bogwero** [comment]
You are more than welcome, I'm glad it is working for you too.
Good luck!
