### ISSUE TITLE
"Empty cache on saving?" - doesn't work

### ISSUE THREAD

**Issue by pawelkierklo** [TeamEver/everblock#8]
When saving changes, it doesn't clear the cache every time

**Comment by CySSoO** [comment]
Hello @pawelkierklo 
Can you try with the latest release? https://github.com/TeamEver/everblock/releases/tag/V5.3.1
Cache clearing has been improved

**Comment by CySSoO** [comment]
Good morning
In addition to the correction announced in a previous message, a button to clear the cache has also been added to the Everblock management pages.
I close this ticket
