### ISSUE TITLE
Block size - add none block

### ISSUE THREAD

**Issue by pawelkierklo** [TeamEver/everblock#9]
Please add non-block element here with value="none"

(no rows class is better for advanced operations)
![image](https://github.com/TeamEver/everblock/assets/26326399/93269a09-18a7-4697-aa13-a9f99aad0332)
my proposition for $item.block,bootstrap_class

>         {foreach from=$everblock item=item}
>             {if isset($item.block.add_container) && $item.block.add_container == 1}
>             <div class="container">
>             {/if}
>             {if isset($item.block.bootstrap_class) && $item.block.bootstrap_class != "none"}
>             <div class="everblock everblock-{$item.block.id_everblock|escape:'htmlall':'UTF-8'} {$item.block.css_class|escape:'htmlall':'UTF-8'} {$item.block.bootstrap_class|escape:'htmlall':'UTF-8'} everhook-{$everhook|escape:'htmlall':'UTF-8'}" id="everblock-{$item.block.id_everblock|escape:'htmlall':'UTF-8'}" data-everposition="{$item.block.position|escape:'htmlall':'UTF-8'}" data-everhook="{$everhook|escape:'htmlall':'UTF-8'}"{if isset($item.block.background) && $item.block.background} style="background-color:{$item.block.background|escape:'htmlall':'UTF-8'};"{/if}>
>             {/if}
>                 {$item.block.content nofilter}
>                 {if isset($item.block.bootstrap_class) && $item.block.bootstrap_class != "none"}
>             </div>
>             {/if}
>             {if isset($item.block.add_container) && $item.block.add_container == 1}
>             </div>
>             {/if}
>         {/foreach}

**Comment by Luifer-dnk** [comment]
And not to load the values of col- and col-md:

**Modify file** /modules/everblock/models/EverblockClass.php

**Edit sentence** "if" **on line 287**:

```
if (!Cache::isStored($cacheId)) {
            $class = 'col-';
            switch ($colNumber) {
                case 1:
                    $class .= '12';
                    break;
                case 2:
                    $class .= '6';
                    break;
                case 3:
                    $class .= '4';
                    break;
                case 4:
                    $class .= '3';
                    break;
                case 6:
                    $class .= '2';
                    break;
                case 7:
                    break;
                default:
                    $class .= '12';
                    break;
            }
            $class .= ' col-md-';
            switch ($colNumber) {
                case 1:
                    $class .= '12';
                    break;
                case 2:
                    $class .= '6';
                    break;
                case 3:
                    $class .= '4';
                    break;
                case 4:
                    $class .= '3';
                    break;
                case 6:
                    $class .= '2';
                    break;
                case 7:
                    break;
                default:
                    $class .= '12';
                    break;
            }
            Cache::store($cacheId, $class);
            return $class;
        }
```
**AND EDIT FILE** /modules/everblock/controllers/admin/AdminEverBlockController.php

Mod "$bootstrapSizes" on line 258:

```
        $bootstrapSizes = [
            [
                'id_bootstrap' => 7,
                'size' => $this->l('None')
            ],
            [
                'id_bootstrap' => 6,
                'size' => $this->l('1/6')
            ],
            [
                'id_bootstrap' => 4,
                'size' => $this->l('1/3')
            ],
            [
                'id_bootstrap' => 3,
                'size' => $this->l('1/4')
            ],
            [
                'id_bootstrap' => 2,
                'size' => $this->l('1/2')
            ],
            [
                'id_bootstrap' => 1,
                'size' => $this->l('100%')
            ],
        ];
```

Greetings.

**Comment by CySSoO** [comment]
Hello @pawelkierklo 
Block size 'none' was added in the latest release. This one is number 0. You can get the latest release here
https://github.com/TeamEver/everblock/releases/tag/V5.3.1
